### ISSUE TITLE
Processing channel clones too fast, results in rate limit

### ISSUE THREAD

**Issue by sot-itna707** [itskekoff/discord-server-copy#11]
No matter what delay I set in config, once it reaches "Processing channels clone" part, it does it too quickly resulting in rate limited. How can this be solved?
![F781FA97-8F27-41C2-BAD2-E0BBE83396C7](https://user-images.githubusercontent.com/128782877/227446344-27f3b7e6-941d-4de5-988a-8dae085a08ad.jpeg)
![7602CF2B-EC63-4765-A662-2FC4DC5FA24E](https://user-images.githubusercontent.com/128782877/227446349-dc412441-cd9f-4a1f-9ed6-9631a306d466.jpeg)

**Comment by itskekoff** [comment]
ok i fixed that shit, thank you for submitting issue and help investigate problem.

**Comment by sot-itna707** [comment]
It fixed the channel clone speed, but now the same issue is happening again once it starts processing emoji.

> ok i fixed that shit, thank you for submitting issue and help investigate problem.

**Comment by sot-itna707** [comment]
![Uploading F0356F0B-591C-4E9A-950A-CC388410B74E.png…]()

**Comment by sot-itna707** [comment]
<img width="1080" alt="9C0ABB21-F8DD-4A3C-9856-2033D1553049" src="https://user-images.githubusercontent.com/128782877/227586132-44197029-637b-4693-ac9a-1b6c679dc7c3.png">

**Comment by sot-itna707** [comment]
I have skipped emojis this time setting it to false. The message cloning works fine so far with the webhook, it skips certain messages, but otherwise emojis are still a problem. But that is not so important.

**Comment by itskekoff** [comment]
yes, my wrong. Fixed.
